version: 2

#default-build: &default-build
#    working_directory: /tmp
#    steps:
#        - checkout
#        - run: |
#            set -x
#            apt update
#            apt install -y devscripts equivs
#            mk-build-deps -i -t "apt --no-install-recommends -y"
#            debuild -us -uc
#            mkdir /tmp/artifacts
#            cp ../apt-btrfs-snapper_* /tmp/artifacts/
#        - store_artifacts:
#            path: /tmp/artifacts


jobs:
    build-xenial:
        docker:
            - image: mumblepins/circleci-dev:xenial-debuild
        working_directory: /tmp
        steps:
            - checkout
            - run: |
                set -x
                apt update
                apt install -y devscripts equivs
                mk-build-deps -i -t "apt --no-install-recommends -y"
                debuild -us -uc
                mkdir /tmp/artifacts
                cp ../apt-btrfs-snapper_* /tmp/artifacts/
            - store_artifacts:
                path: /tmp/artifacts
    build-zesty:
        docker:
            - image: mumblepins/circleci-dev:zesty-debuild
        working_directory: /tmp
        steps:
            - checkout
            - run: |
                set -x
                apt update
                apt install -y devscripts equivs
                mk-build-deps -i -t "apt --no-install-recommends -y"
                debuild -us -uc
                mkdir /tmp/artifacts
                cp ../apt-btrfs-snapper_* /tmp/artifacts/
            - store_artifacts:
                path: /tmp/artifacts


workflows:
    version: 2
    build-all:
        jobs:
            - build-xenial
            - build-zesty

